class AiProxyService < Formula
  desc "Pool AI subscriptions and API keys behind one endpoint with an admin panel"
  homepage "https://github.com/veildawn/ai-proxy-releases"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # Prebuilt release archives; the version is parsed from the url. This file is
  # regenerated by the Release workflow in veildawn/ai-proxy-releases on every
  # release — bump it by cutting a release, never by hand.
  on_macos do
    on_arm do
      url "https://github.com/veildawn/ai-proxy-releases/releases/download/v0.17.97/ai-proxy-service_0.17.97_darwin_arm64.tar.gz"
      sha256 "8559e34b6545fa4a310041a214bfe61ce0aaa73299a576b96040924561f333c7"
    end
    on_intel do
      url "https://github.com/veildawn/ai-proxy-releases/releases/download/v0.17.97/ai-proxy-service_0.17.97_darwin_amd64.tar.gz"
      sha256 "3bf3ecea50b95c5b79b8c3696e0cb9cf85737a35ded9d1df96642ff76ffa9689"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/veildawn/ai-proxy-releases/releases/download/v0.17.97/ai-proxy-service_0.17.97_linux_arm64.tar.gz"
      sha256 "577ea36081124ff71c6ab8af99b363741ead3786370d99b8d415f3c39ca8b087"
    end
    on_intel do
      url "https://github.com/veildawn/ai-proxy-releases/releases/download/v0.17.97/ai-proxy-service_0.17.97_linux_amd64.tar.gz"
      sha256 "bda4f633d207ab43c2f4bba42ebd8c7d58975c98c3234bed3512c501d2241d7e"
    end
  end

  # Everything the app writes lives under var/ai-proxy-service — the same
  # single-DATA_DIR layout install.sh uses: .env is loaded from the working
  # directory, secrets.env and setup-token are written beside config.yaml, and
  # logging.dir + chat assets default to ./data/ relative to it.
  def install
    bin.install "ai-proxy-service"
    (var/"ai-proxy-service").install "config.example.yaml", ".env.example"
  end

  def post_install
    dir = var/"ai-proxy-service"
    # Seeded once and never overwritten on upgrade — config.yaml may have been
    # edited by hand (same rule as install.sh).
    unless (dir/"config.yaml").exist?
      cp dir/"config.example.yaml", dir/"config.yaml"
      # The binary lives in a versioned keg owned by brew; an in-place
      # self-update would swap it under the old version's Cellar path and the
      # next `brew upgrade` would silently revert it. brew is the update path.
      inreplace dir/"config.yaml", "  allow_self_update: true", "  allow_self_update: false"
    end
    unless (dir/".env").exist?
      cp dir/".env.example", dir/".env"
      inreplace dir/".env", "APP_ENV=development", "APP_ENV=production"
    end
  end

  service do
    run [opt_bin/"ai-proxy-service", "serve", "--config", var/"ai-proxy-service/config.yaml"]
    working_dir var/"ai-proxy-service"
    keep_alive true
    environment_variables APP_ENV: "production"
    log_path var/"log/ai-proxy-service.out.log"
    error_log_path var/"log/ai-proxy-service.err.log"
  end

  def caveats
    <<~EOS
      Point it at a database first — database.dsn in
        #{var}/ai-proxy-service/config.yaml
      or DATABASE_URL in
        #{var}/ai-proxy-service/.env

      Then start it:
        brew services start ai-proxy-service
      or run it by hand:
        ai-proxy-service serve --config #{var}/ai-proxy-service/config.yaml

      Finish setup at http://localhost:8080/setup with the one-time token from:
        cat #{var}/ai-proxy-service/setup-token

      Update with: brew upgrade ai-proxy-service
      Starting runs database migrations; the in-app self-update is disabled on
      purpose — brew owns this binary.
    EOS
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/ai-proxy-service version").strip
  end
end
